org: leonardohc
service: api-s3-bucket

provider:
  name: aws
  runtime: python3.12	
  # Default memory size for functions (default: 256MB)
  memorySize: 256
  iam:
    role: arn:aws:iam::568587190313:role/LabRole

functions:
  crear_bucket:
    handler: crear_bucket.lambda_handler
    memorySize: 512
    events:
      - http:
        path: /s3/bucket/crear_bucket
        method: post
        cors: true
        integration: lambda
  crear_carpeta:
    handler: crear_carpeta.lambda_handler
    memorySize: 512
    events:
      - http:
        path: /s3/bucket/crear_carpeta
        method: post
        cors: true
        integration: lambda
